configs:
- app_id: first
  limits:
  - api: /home/hello
    limit: 1000
    unit: 10
    auto: true
  - api: /home/hello1
    limit: 100
    unit: 100
    auto: false
- app_id: second
  limits:
    - api: /home/hello2
      limit: 100
      unit: 1000
    - api: /home/hello3
      limit: 1000
      unit: 1000



